/**
 * Mapping of short demo biomarker codes to full database codes
 * Used to match demo data codes with actual biomarker metadata
 */
export const DEMO_TO_DB_CODE: Record<string, string> = {
  // Энергия и восстановление
  HB: "Гемоглобин (Hb)",
  HCT: "Гематокрит (HCT)",
  RBC: "Эритроциты (RBC)",
  ESR: "СОЭ",
  FERR: "Ферритин",
  MCV: "MCV",
  MCHC: "MCH / MCHC",
  PLT: "Тромбоциты (PLT)",
  RETIC: "Ретикулоциты",
  HAPTO: "Гаптоглобин",
  FE: "Железо сыворотки (Fe)",
  TIBC: "ОЖСС",
  TRANSF: "Трансферрин",
  TSAT: "Насыщение трансферрина",
  FOLATE: "Фолиевая кислота",
  
  // Воспалительная и иммунная система
  CRP: "CRP (hs-CRP)",
  WBC: "Лейкоциты (WBC)",
  NEUT: "Нейтрофилы",
  LYMPH: "Лимфоциты",
  MONO: "Моноциты",
  EOS: "Эозинофилы",
  BASO: "Базофилы",
  IL6: "IL-6",
  TNF: "TNF-α",
  IGM: "IgM",
  IGG: "IgG",
  IGA: "IgA",
  IGE: "IgE",
  CD3: "CD3 (T-лимфоциты)",
  CD4: "CD4 (T-хелперы)",
  CD8: "CD8 (T-супрессоры)",
  CD19: "CD19 (B-лимфоциты)",
  NK: "NK-клетки",
  
  // Сердечно-сосудистая система
  CHOL: "Общий холестерин (TC)",
  LDL: "ЛПНП (LDL)",
  HDL: "ЛПВП (HDL)",
  TG: "Триглицериды (TG)",
  VLDL: "ЛПОНП (VLDL)",
  APOA1: "ApoA1",
  APOB: "ApoB",
  CA: "Коэффициент атерогенности",
  LPA: "Липопротеин(a)",
  HCY: "Гомоцистеин",
  NTPROBNP: "NT-proBNP",
  TROP: "Тропонин I",
  MYO: "Миоглобин",
  CPK: "КФК",
  LDH: "ЛДГ",
  
  // Обмен веществ и детоксикация
  GLU: "Глюкоза",
  HBA1C: "HbA1c",
  CREA: "Креатинин",
  ALT: "ALT",
  AST: "AST",
  GGT: "GGT",
  ALP: "ALP",
  BIL: "Билирубин",
  TP: "Общий белок",
  UREA: "Мочевина",
  NA: "Натрий (Na)",
  K: "Калий (K)",
  CL: "Хлор (Cl)",
  CACL: "Кальций (Ca)",
  
  // Эндокринная и стрессовая система
  TEST: "Тестостерон общий",
  ESTR: "Эстрадиол (E2)",
  SHBG: "SHBG",
  DHEAS: "DHEA-S",
  VITD: "25-ОН витамин D",
  TSH: "ТТГ",
  FT4: "Т4 свободный",
  FT3: "Т3 свободный (FT3)",
  CORT: "Кортизол",
  INS: "Инсулин",
  IGF1: "IGF-1",
};
