/**
 * Mapping of short demo biomarker codes to full database codes
 * Used to match demo data codes with actual biomarker metadata
 */
export const DEMO_TO_DB_CODE: Record<string, string> = {
  // Энергия и восстановление
  HB: "Hb",
  HCT: "HCT",
  RBC: "RBC",
  ESR: "ESR",
  FERR: "FERR",
  MCV: "MCV",
  MCHC: "MCH",
  PLT: "PLT",
  FE: "Fe",
  TRANSF: "TRANSF",
  FOLATE: "B9",
  B12: "B12",
  
  // Воспалительная и иммунная система
  CRP: "hs-CRP",
  WBC: "WBC",
  NEUT: "NEUT",
  LYMPH: "LYMPH",
  MONO: "MONO",
  EOS: "EOS",
  BASO: "BASO",
  IL6: "IL-6",
  TNF: "TNF-α",
  IGM: "IgM",
  IGG: "IgG",
  CD3: "CD3+",
  CD4: "CD4+",
  CD8: "CD8+",
  NK: "NK",
  
  // Сердечно-сосудистая система
  CHOL: "TC",
  LDL: "LDL",
  HDL: "HDL",
  TG: "TG",
  VLDL: "VLDL",
  APOA1: "ApoA1",
  APOB: "ApoB",
  CA: "ИА",
  LPA: "Lp(a)",
  NONHDL: "non-HDL",
  ABRA: "ApoB/A1",
  HCY: "HCY",
  NTPROBNP: "NT-proBNP",
  CPK: "КФК",
  LDH: "ЛДГ",
  
  // Обмен веществ и детоксикация
  GLU: "GLU",
  HBA1C: "HbA1c",
  CREA: "CREA",
  ALT: "АЛТ",
  AST: "АСТ",
  GGT: "ГГТ",
  ALP: "ЩФ",
  BIL: "BIL",
  TP: "TP",
  ALB: "ALB",
  UREA: "UREA",
  NA: "Na",
  K: "K",
  CL: "Cl",
  CACL: "Ca",
  MG: "Mg",
  ZN: "Zn",
  CU: "Cu",
  SE: "Se",
  COQ10: "CoQ10",
  LACT: "LACT",
  MDA: "MDA",
  OAS: "OAS",
  
  // Эндокринная и стрессовая система
  TEST: "TEST",
  ESTR: "E2",
  E1: "E1",
  E3: "E3",
  SHBG: "SHBG",
  DHEAS: "DHEA-S",
  VITD: "25-OH D",
  TSH: "ТТГ",
  FT4: "Т4 св.",
  FT3: "Т3 св.",
  CORT: "CORT",
  INS: "INS",
  IGF1: "IGF-1",
  HOMAIR: "HOMA-IR",
};
