/**
 * Mapping of short demo biomarker codes to full database codes
 * Used to match demo data codes with actual biomarker metadata
 */
export const DEMO_TO_DB_CODE: Record<string, string> = {
  // Энергия и восстановление
  HB: "Гемоглобин (Hb)",
  HCT: "Гематокрит (HCT)",
  RBC: "Эритроциты (RBC)",
  ESR: "СОЭ",
  FERR: "Ферритин",
  MCV: "MCV",
  MCHC: "MCH / MCHC",
  PLT: "Тромбоциты (PLT)",
  FE: "Железо",
  TRANSF: "Трансферрин",
  FOLATE: "Фолиевая кислота (B9)",
  B12: "Витамин B12",
  
  // Воспалительная и иммунная система
  CRP: "CRP (hs-CRP)",
  WBC: "Лейкоциты (WBC)",
  NEUT: "Нейтрофилы",
  LYMPH: "Лимфоциты",
  MONO: "Моноциты",
  EOS: "Эозинофилы",
  BASO: "Базофилы",
  IL6: "IL-6",
  TNF: "TNF-α",
  IGM: "IgM",
  IGG: "IgG",
  CD3: "CD3+ (T-лимфоциты)",
  CD4: "CD4+ (T-хелперы)",
  CD8: "CD8+ (T-супрессоры)",
  NK: "NK-клетки (CD16+CD56+)",
  
  // Сердечно-сосудистая система
  CHOL: "Общий холестерин (TC)",
  LDL: "ЛПНП (LDL)",
  HDL: "ЛПВП (HDL)",
  TG: "Триглицериды (TG)",
  VLDL: "ЛПОНП (VLDL)",
  APOA1: "ApoA1",
  APOB: "ApoB",
  CA: "Индекс атерогенности",
  LPA: "Lp(a)",
  NONHDL: "не-HDL холестерин",
  ABRA: "Соотношение ApoB/ApoA1",
  HCY: "Гомоцистеин",
  NTPROBNP: "NT-proBNP",
  CPK: "Креатинкиназа (КФК)",
  LDH: "Лактатдегидрогеназа (ЛДГ)",
  
  // Обмен веществ и детоксикация
  GLU: "Глюкоза",
  HBA1C: "HbA1c",
  CREA: "Креатинин",
  ALT: "ALT",
  AST: "AST",
  GGT: "GGT",
  ALP: "ALP",
  BIL: "Билирубин",
  TP: "Общий белок",
  ALB: "Альбумин",
  UREA: "Мочевина",
  NA: "Натрий (Na)",
  K: "Калий (K)",
  CL: "Хлор (Cl)",
  CACL: "Кальций (Ca)",
  MG: "Магний (сыворотка)",
  ZN: "Цинк",
  CU: "Медь",
  SE: "Селен",
  COQ10: "Коэнзим Q10 (plasma)",
  LACT: "Лактат",
  MDA: "Малоновый диальдегид",
  OAS: "Общий антиоксидантный статус (OAS)",
  
  // Эндокринная и стрессовая система
  TEST: "Тестостерон общий",
  ESTR: "Эстрадиол (E2)",
  E1: "Эстрон (E1)",
  E3: "Эстриол (E3)",
  SHBG: "SHBG",
  DHEAS: "DHEA-S",
  VITD: "25-ОН витамин D",
  TSH: "ТТГ",
  FT4: "Т4 свободный",
  FT3: "Т3 свободный",
  CORT: "Кортизол",
  INS: "Инсулин",
  IGF1: "IGF-1",
  HOMAIR: "HOMA-IR (расчётный)",
};
