project_id = "ilxgodhosirhhkffqryw"

[functions]
  [functions.analyze-risk-zones]
    verify_jwt = true
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.cleanup-prescriptions]
    verify_jwt = false
  [functions.delete-user]
    verify_jwt = true
  [functions.health-assistant]
    verify_jwt = true
  [functions.register-staff]
    verify_jwt = false
  [functions.sanitize-analysis-data]
    verify_jwt = true
  [functions.finalize-analysis]
    verify_jwt = false
