project_id = "ilxgodhosirhhkffqryw"

[functions.health-assistant]
verify_jwt = true

[functions.register-staff]
verify_jwt = false

[functions.analyze-risk-zones]
verify_jwt = true

[functions.sanitize-analysis-data]
verify_jwt = true

[functions.delete-user]
verify_jwt = true
