events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;

    server {
        listen 127.0.0.1:8080;
        root /usr/share/nginx/html;
        index index.html;

        location /assets/ {
            try_files $uri =404;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
