-- Update demo_data_templates with complete 71 biomarkers across 4 analyses
-- Male data: 71 biomarkers × 4 analyses = 284 biomarker entries
-- Female data: 71 biomarkers × 4 analyses = 284 biomarker entries

UPDATE demo_data_templates
SET male_data = '{
  "profile": {
    "name": "Иван Петров",
    "gender": "male",
    "birth_date": "1980-01-15",
    "weight": 85,
    "height": 178
  },
  "analyses": [
    {
      "date": "2024-04-15",
      "note": "Первичное обследование",
      "lab_name": "Медицинский центр \"Здоровье\"",
      "biological_age": 49,
      "health_index": 68,
      "status": "processed",
      "analysis_index": 0
    },
    {
      "date": "2024-07-15",
      "note": "Контрольное обследование через 3 месяца",
      "lab_name": "Медицинский центр \"Здоровье\"",
      "biological_age": 47.5,
      "health_index": 72,
      "status": "processed",
      "analysis_index": 1
    },
    {
      "date": "2024-10-15",
      "note": "Повторное обследование",
      "lab_name": "Медицинский центр \"Здоровье\"",
      "biological_age": 46,
      "health_index": 78,
      "status": "processed",
      "analysis_index": 2
    },
    {
      "date": "2025-01-15",
      "note": "Плановое обследование",
      "lab_name": "Медицинский центр \"Здоровье\"",
      "biological_age": 46.5,
      "health_index": 76,
      "status": "processed",
      "analysis_index": 3
    }
  ],
  "biomarkers": [
    {"code": "HB", "value": 148, "unit": "г/л", "analysis_index": 0},
    {"code": "HB", "value": 152, "unit": "г/л", "analysis_index": 1},
    {"code": "HB", "value": 155, "unit": "г/л", "analysis_index": 2},
    {"code": "HB", "value": 153, "unit": "г/л", "analysis_index": 3},
    {"code": "RBC", "value": 4.8, "unit": "×10¹²/л", "analysis_index": 0},
    {"code": "RBC", "value": 4.95, "unit": "×10¹²/л", "analysis_index": 1},
    {"code": "RBC", "value": 5.1, "unit": "×10¹²/л", "analysis_index": 2},
    {"code": "RBC", "value": 5.0, "unit": "×10¹²/л", "analysis_index": 3},
    {"code": "HCT", "value": 43, "unit": "%", "analysis_index": 0},
    {"code": "HCT", "value": 44, "unit": "%", "analysis_index": 1},
    {"code": "HCT", "value": 45, "unit": "%", "analysis_index": 2},
    {"code": "HCT", "value": 44.5, "unit": "%", "analysis_index": 3},
    {"code": "MCV", "value": 92, "unit": "фл", "analysis_index": 0},
    {"code": "MCV", "value": 91, "unit": "фл", "analysis_index": 1},
    {"code": "MCV", "value": 90, "unit": "фл", "analysis_index": 2},
    {"code": "MCV", "value": 90, "unit": "фл", "analysis_index": 3},
    {"code": "MCHC", "value": 28, "unit": "пг", "analysis_index": 0},
    {"code": "MCHC", "value": 28.5, "unit": "пг", "analysis_index": 1},
    {"code": "MCHC", "value": 29, "unit": "пг", "analysis_index": 2},
    {"code": "MCHC", "value": 29, "unit": "пг", "analysis_index": 3},
    {"code": "PLT", "value": 245, "unit": "×10⁹/л", "analysis_index": 0},
    {"code": "PLT", "value": 250, "unit": "×10⁹/л", "analysis_index": 1},
    {"code": "PLT", "value": 255, "unit": "×10⁹/л", "analysis_index": 2},
    {"code": "PLT", "value": 252, "unit": "×10⁹/л", "analysis_index": 3},
    {"code": "ESR", "value": 8, "unit": "мм/ч", "analysis_index": 0},
    {"code": "ESR", "value": 6, "unit": "мм/ч", "analysis_index": 1},
    {"code": "ESR", "value": 5, "unit": "мм/ч", "analysis_index": 2},
    {"code": "ESR", "value": 5, "unit": "мм/ч", "analysis_index": 3},
    {"code": "FERR", "value": 85, "unit": "нг/мл", "analysis_index": 0},
    {"code": "FERR", "value": 120, "unit": "нг/мл", "analysis_index": 1},
    {"code": "FERR", "value": 145, "unit": "нг/мл", "analysis_index": 2},
    {"code": "FERR", "value": 140, "unit": "нг/мл", "analysis_index": 3},
    {"code": "FE", "value": 14, "unit": "мкмоль/л", "analysis_index": 0},
    {"code": "FE", "value": 17, "unit": "мкмоль/л", "analysis_index": 1},
    {"code": "FE", "value": 19, "unit": "мкмоль/л", "analysis_index": 2},
    {"code": "FE", "value": 18, "unit": "мкмоль/л", "analysis_index": 3},
    {"code": "TIBC", "value": 58, "unit": "мкмоль/л", "analysis_index": 0},
    {"code": "TIBC", "value": 56, "unit": "мкмоль/л", "analysis_index": 1},
    {"code": "TIBC", "value": 54, "unit": "мкмоль/л", "analysis_index": 2},
    {"code": "TIBC", "value": 55, "unit": "мкмоль/л", "analysis_index": 3},
    {"code": "TRANSF", "value": 2.5, "unit": "г/л", "analysis_index": 0},
    {"code": "TRANSF", "value": 2.7, "unit": "г/л", "analysis_index": 1},
    {"code": "TRANSF", "value": 2.9, "unit": "г/л", "analysis_index": 2},
    {"code": "TRANSF", "value": 2.8, "unit": "г/л", "analysis_index": 3},
    {"code": "TSAT", "value": 24, "unit": "%", "analysis_index": 0},
    {"code": "TSAT", "value": 28, "unit": "%", "analysis_index": 1},
    {"code": "TSAT", "value": 32, "unit": "%", "analysis_index": 2},
    {"code": "TSAT", "value": 30, "unit": "%", "analysis_index": 3},
    {"code": "RETIC", "value": 1.2, "unit": "%", "analysis_index": 0},
    {"code": "RETIC", "value": 1.1, "unit": "%", "analysis_index": 1},
    {"code": "RETIC", "value": 1.0, "unit": "%", "analysis_index": 2},
    {"code": "RETIC", "value": 1.0, "unit": "%", "analysis_index": 3},
    {"code": "HAPTO", "value": 1.2, "unit": "г/л", "analysis_index": 0},
    {"code": "HAPTO", "value": 1.3, "unit": "г/л", "analysis_index": 1},
    {"code": "HAPTO", "value": 1.4, "unit": "г/л", "analysis_index": 2},
    {"code": "HAPTO", "value": 1.35, "unit": "г/л", "analysis_index": 3},
    {"code": "FOLATE", "value": 8, "unit": "нг/мл", "analysis_index": 0},
    {"code": "FOLATE", "value": 10, "unit": "нг/мл", "analysis_index": 1},
    {"code": "FOLATE", "value": 12, "unit": "нг/мл", "analysis_index": 2},
    {"code": "FOLATE", "value": 11, "unit": "нг/мл", "analysis_index": 3},
    {"code": "WBC", "value": 7.2, "unit": "×10⁹/л", "analysis_index": 0},
    {"code": "WBC", "value": 6.8, "unit": "×10⁹/л", "analysis_index": 1},
    {"code": "WBC", "value": 6.2, "unit": "×10⁹/л", "analysis_index": 2},
    {"code": "WBC", "value": 6.4, "unit": "×10⁹/л", "analysis_index": 3},
    {"code": "NEUT", "value": 65, "unit": "%", "analysis_index": 0},
    {"code": "NEUT", "value": 62, "unit": "%", "analysis_index": 1},
    {"code": "NEUT", "value": 60, "unit": "%", "analysis_index": 2},
    {"code": "NEUT", "value": 61, "unit": "%", "analysis_index": 3},
    {"code": "LYMPH", "value": 25, "unit": "%", "analysis_index": 0},
    {"code": "LYMPH", "value": 28, "unit": "%", "analysis_index": 1},
    {"code": "LYMPH", "value": 30, "unit": "%", "analysis_index": 2},
    {"code": "LYMPH", "value": 29, "unit": "%", "analysis_index": 3},
    {"code": "MONO", "value": 7, "unit": "%", "analysis_index": 0},
    {"code": "MONO", "value": 6.5, "unit": "%", "analysis_index": 1},
    {"code": "MONO", "value": 6, "unit": "%", "analysis_index": 2},
    {"code": "MONO", "value": 6, "unit": "%", "analysis_index": 3},
    {"code": "EOS", "value": 2, "unit": "%", "analysis_index": 0},
    {"code": "EOS", "value": 2.5, "unit": "%", "analysis_index": 1},
    {"code": "EOS", "value": 3, "unit": "%", "analysis_index": 2},
    {"code": "EOS", "value": 3, "unit": "%", "analysis_index": 3},
    {"code": "BASO", "value": 0.5, "unit": "%", "analysis_index": 0},
    {"code": "BASO", "value": 0.5, "unit": "%", "analysis_index": 1},
    {"code": "BASO", "value": 0.5, "unit": "%", "analysis_index": 2},
    {"code": "BASO", "value": 0.5, "unit": "%", "analysis_index": 3},
    {"code": "CRP", "value": 4.2, "unit": "мг/л", "analysis_index": 0},
    {"code": "CRP", "value": 3.2, "unit": "мг/л", "analysis_index": 1},
    {"code": "CRP", "value": 2.1, "unit": "мг/л", "analysis_index": 2},
    {"code": "CRP", "value": 2.5, "unit": "мг/л", "analysis_index": 3},
    {"code": "IL6", "value": 6.5, "unit": "пг/мл", "analysis_index": 0},
    {"code": "IL6", "value": 5.2, "unit": "пг/мл", "analysis_index": 1},
    {"code": "IL6", "value": 3.8, "unit": "пг/мл", "analysis_index": 2},
    {"code": "IL6", "value": 4.2, "unit": "пг/мл", "analysis_index": 3},
    {"code": "TNF", "value": 7.8, "unit": "пг/мл", "analysis_index": 0},
    {"code": "TNF", "value": 6.2, "unit": "пг/мл", "analysis_index": 1},
    {"code": "TNF", "value": 4.5, "unit": "пг/мл", "analysis_index": 2},
    {"code": "TNF", "value": 5.0, "unit": "пг/мл", "analysis_index": 3},
    {"code": "IGM", "value": 1.2, "unit": "г/л", "analysis_index": 0},
    {"code": "IGM", "value": 1.3, "unit": "г/л", "analysis_index": 1},
    {"code": "IGM", "value": 1.4, "unit": "г/л", "analysis_index": 2},
    {"code": "IGM", "value": 1.35, "unit": "г/л", "analysis_index": 3},
    {"code": "IGG", "value": 11, "unit": "г/л", "analysis_index": 0},
    {"code": "IGG", "value": 11.5, "unit": "г/л", "analysis_index": 1},
    {"code": "IGG", "value": 12, "unit": "г/л", "analysis_index": 2},
    {"code": "IGG", "value": 11.8, "unit": "г/л", "analysis_index": 3},
    {"code": "IGA", "value": 2.2, "unit": "г/л", "analysis_index": 0},
    {"code": "IGA", "value": 2.3, "unit": "г/л", "analysis_index": 1},
    {"code": "IGA", "value": 2.4, "unit": "г/л", "analysis_index": 2},
    {"code": "IGA", "value": 2.35, "unit": "г/л", "analysis_index": 3},
    {"code": "IGE", "value": 45, "unit": "МЕ/мл", "analysis_index": 0},
    {"code": "IGE", "value": 42, "unit": "МЕ/мл", "analysis_index": 1},
    {"code": "IGE", "value": 38, "unit": "МЕ/мл", "analysis_index": 2},
    {"code": "IGE", "value": 40, "unit": "МЕ/мл", "analysis_index": 3},
    {"code": "CD3", "value": 68, "unit": "%", "analysis_index": 0},
    {"code": "CD3", "value": 70, "unit": "%", "analysis_index": 1},
    {"code": "CD3", "value": 72, "unit": "%", "analysis_index": 2},
    {"code": "CD3", "value": 71, "unit": "%", "analysis_index": 3},
    {"code": "CD4", "value": 42, "unit": "%", "analysis_index": 0},
    {"code": "CD4", "value": 43, "unit": "%", "analysis_index": 1},
    {"code": "CD4", "value": 45, "unit": "%", "analysis_index": 2},
    {"code": "CD4", "value": 44, "unit": "%", "analysis_index": 3},
    {"code": "CD8", "value": 28, "unit": "%", "analysis_index": 0},
    {"code": "CD8", "value": 27, "unit": "%", "analysis_index": 1},
    {"code": "CD8", "value": 26, "unit": "%", "analysis_index": 2},
    {"code": "CD8", "value": 27, "unit": "%", "analysis_index": 3},
    {"code": "CD19", "value": 12, "unit": "%", "analysis_index": 0},
    {"code": "CD19", "value": 13, "unit": "%", "analysis_index": 1},
    {"code": "CD19", "value": 14, "unit": "%", "analysis_index": 2},
    {"code": "CD19", "value": 13.5, "unit": "%", "analysis_index": 3},
    {"code": "NK", "value": 15, "unit": "%", "analysis_index": 0},
    {"code": "NK", "value": 16, "unit": "%", "analysis_index": 1},
    {"code": "NK", "value": 17, "unit": "%", "analysis_index": 2},
    {"code": "NK", "value": 16.5, "unit": "%", "analysis_index": 3},
    {"code": "CHOL", "value": 6.2, "unit": "ммоль/л", "analysis_index": 0},
    {"code": "CHOL", "value": 5.8, "unit": "ммоль/л", "analysis_index": 1},
    {"code": "CHOL", "value": 5.3, "unit": "ммоль/л", "analysis_index": 2},
    {"code": "CHOL", "value": 5.5, "unit": "ммоль/л", "analysis_index": 3},
    {"code": "LDL", "value": 4.1, "unit": "ммоль/л", "analysis_index": 0},
    {"code": "LDL", "value": 3.6, "unit": "ммоль/л", "analysis_index": 1},
    {"code": "LDL", "value": 3.2, "unit": "ммоль/л", "analysis_index": 2},
    {"code": "LDL", "value": 3.4, "unit": "ммоль/л", "analysis_index": 3},
    {"code": "HDL", "value": 1.1, "unit": "ммоль/л", "analysis_index": 0},
    {"code": "HDL", "value": 1.25, "unit": "ммоль/л", "analysis_index": 1},
    {"code": "HDL", "value": 1.35, "unit": "ммоль/л", "analysis_index": 2},
    {"code": "HDL", "value": 1.3, "unit": "ммоль/л", "analysis_index": 3},
    {"code": "TG", "value": 2.2, "unit": "ммоль/л", "analysis_index": 0},
    {"code": "TG", "value": 1.9, "unit": "ммоль/л", "analysis_index": 1},
    {"code": "TG", "value": 1.5, "unit": "ммоль/л", "analysis_index": 2},
    {"code": "TG", "value": 1.6, "unit": "ммоль/л", "analysis_index": 3},
    {"code": "VLDL", "value": 1.0, "unit": "ммоль/л", "analysis_index": 0},
    {"code": "VLDL", "value": 0.9, "unit": "ммоль/л", "analysis_index": 1},
    {"code": "VLDL", "value": 0.7, "unit": "ммоль/л", "analysis_index": 2},
    {"code": "VLDL", "value": 0.75, "unit": "ммоль/л", "analysis_index": 3},
    {"code": "APOA1", "value": 1.2, "unit": "г/л", "analysis_index": 0},
    {"code": "APOA1", "value": 1.35, "unit": "г/л", "analysis_index": 1},
    {"code": "APOA1", "value": 1.45, "unit": "г/л", "analysis_index": 2},
    {"code": "APOA1", "value": 1.4, "unit": "г/л", "analysis_index": 3},
    {"code": "APOB", "value": 1.15, "unit": "г/л", "analysis_index": 0},
    {"code": "APOB", "value": 1.05, "unit": "г/л", "analysis_index": 1},
    {"code": "APOB", "value": 0.95, "unit": "г/л", "analysis_index": 2},
    {"code": "APOB", "value": 0.98, "unit": "г/л", "analysis_index": 3},
    {"code": "CA", "value": 4.7, "unit": "усл.ед.", "analysis_index": 0},
    {"code": "CA", "value": 3.8, "unit": "усл.ед.", "analysis_index": 1},
    {"code": "CA", "value": 2.9, "unit": "усл.ед.", "analysis_index": 2},
    {"code": "CA", "value": 3.2, "unit": "усл.ед.", "analysis_index": 3},
    {"code": "LPA", "value": 28, "unit": "мг/дл", "analysis_index": 0},
    {"code": "LPA", "value": 26, "unit": "мг/дл", "analysis_index": 1},
    {"code": "LPA", "value": 24, "unit": "мг/дл", "analysis_index": 2},
    {"code": "LPA", "value": 25, "unit": "мг/дл", "analysis_index": 3},
    {"code": "HCY", "value": 14, "unit": "мкмоль/л", "analysis_index": 0},
    {"code": "HCY", "value": 12, "unit": "мкмоль/л", "analysis_index": 1},
    {"code": "HCY", "value": 10, "unit": "мкмоль/л", "analysis_index": 2},
    {"code": "HCY", "value": 11, "unit": "мкмоль/л", "analysis_index": 3},
    {"code": "NTPROBNP", "value": 85, "unit": "пг/мл", "analysis_index": 0},
    {"code": "NTPROBNP", "value": 78, "unit": "пг/мл", "analysis_index": 1},
    {"code": "NTPROBNP", "value": 72, "unit": "пг/мл", "analysis_index": 2},
    {"code": "NTPROBNP", "value": 75, "unit": "пг/мл", "analysis_index": 3},
    {"code": "TROP", "value": 0.008, "unit": "нг/мл", "analysis_index": 0},
    {"code": "TROP", "value": 0.007, "unit": "нг/мл", "analysis_index": 1},
    {"code": "TROP", "value": 0.006, "unit": "нг/мл", "analysis_index": 2},
    {"code": "TROP", "value": 0.006, "unit": "нг/мл", "analysis_index": 3},
    {"code": "MYO", "value": 42, "unit": "нг/мл", "analysis_index": 0},
    {"code": "MYO", "value": 38, "unit": "нг/мл", "analysis_index": 1},
    {"code": "MYO", "value": 35, "unit": "нг/мл", "analysis_index": 2},
    {"code": "MYO", "value": 36, "unit": "нг/мл", "analysis_index": 3},
    {"code": "CPK", "value": 165, "unit": "Ед/л", "analysis_index": 0},
    {"code": "CPK", "value": 158, "unit": "Ед/л", "analysis_index": 1},
    {"code": "CPK", "value": 152, "unit": "Ед/л", "analysis_index": 2},
    {"code": "CPK", "value": 155, "unit": "Ед/л", "analysis_index": 3},
    {"code": "LDH", "value": 185, "unit": "Ед/л", "analysis_index": 0},
    {"code": "LDH", "value": 178, "unit": "Ед/л", "analysis_index": 1},
    {"code": "LDH", "value": 172, "unit": "Ед/л", "analysis_index": 2},
    {"code": "LDH", "value": 175, "unit": "Ед/л", "analysis_index": 3},
    {"code": "GLU", "value": 6.1, "unit": "ммоль/л", "analysis_index": 0},
    {"code": "GLU", "value": 5.8, "unit": "ммоль/л", "analysis_index": 1},
    {"code": "GLU", "value": 5.5, "unit": "ммоль/л", "analysis_index": 2},
    {"code": "GLU", "value": 5.6, "unit": "ммоль/л", "analysis_index": 3},
    {"code": "HBA1C", "value": 6.1, "unit": "%", "analysis_index": 0},
    {"code": "HBA1C", "value": 5.8, "unit": "%", "analysis_index": 1},
    {"code": "HBA1C", "value": 5.5, "unit": "%", "analysis_index": 2},
    {"code": "HBA1C", "value": 5.6, "unit": "%", "analysis_index": 3},
    {"code": "INS", "value": 18, "unit": "мкЕд/мл", "analysis_index": 0},
    {"code": "INS", "value": 15, "unit": "мкЕд/мл", "analysis_index": 1},
    {"code": "INS", "value": 12, "unit": "мкЕд/мл", "analysis_index": 2},
    {"code": "INS", "value": 13, "unit": "мкЕд/мл", "analysis_index": 3},
    {"code": "CREA", "value": 95, "unit": "мкмоль/л", "analysis_index": 0},
    {"code": "CREA", "value": 92, "unit": "мкмоль/л", "analysis_index": 1},
    {"code": "CREA", "value": 90, "unit": "мкмоль/л", "analysis_index": 2},
    {"code": "CREA", "value": 91, "unit": "мкмоль/л", "analysis_index": 3},
    {"code": "UREA", "value": 5.8, "unit": "ммоль/л", "analysis_index": 0},
    {"code": "UREA", "value": 5.5, "unit": "ммоль/л", "analysis_index": 1},
    {"code": "UREA", "value": 5.2, "unit": "ммоль/л", "analysis_index": 2},
    {"code": "UREA", "value": 5.3, "unit": "ммоль/л", "analysis_index": 3},
    {"code": "ALT", "value": 35, "unit": "Ед/л", "analysis_index": 0},
    {"code": "ALT", "value": 30, "unit": "Ед/л", "analysis_index": 1},
    {"code": "ALT", "value": 26, "unit": "Ед/л", "analysis_index": 2},
    {"code": "ALT", "value": 28, "unit": "Ед/л", "analysis_index": 3},
    {"code": "AST", "value": 32, "unit": "Ед/л", "analysis_index": 0},
    {"code": "AST", "value": 28, "unit": "Ед/л", "analysis_index": 1},
    {"code": "AST", "value": 24, "unit": "Ед/л", "analysis_index": 2},
    {"code": "AST", "value": 26, "unit": "Ед/л", "analysis_index": 3},
    {"code": "GGT", "value": 42, "unit": "Ед/л", "analysis_index": 0},
    {"code": "GGT", "value": 36, "unit": "Ед/л", "analysis_index": 1},
    {"code": "GGT", "value": 30, "unit": "Ед/л", "analysis_index": 2},
    {"code": "GGT", "value": 32, "unit": "Ед/л", "analysis_index": 3},
    {"code": "ALP", "value": 75, "unit": "Ед/л", "analysis_index": 0},
    {"code": "ALP", "value": 72, "unit": "Ед/л", "analysis_index": 1},
    {"code": "ALP", "value": 68, "unit": "Ед/л", "analysis_index": 2},
    {"code": "ALP", "value": 70, "unit": "Ед/л", "analysis_index": 3},
    {"code": "BIL", "value": 15, "unit": "мкмоль/л", "analysis_index": 0},
    {"code": "BIL", "value": 14, "unit": "мкмоль/л", "analysis_index": 1},
    {"code": "BIL", "value": 13, "unit": "мкмоль/л", "analysis_index": 2},
    {"code": "BIL", "value": 13.5, "unit": "мкмоль/л", "analysis_index": 3},
    {"code": "TP", "value": 72, "unit": "г/л", "analysis_index": 0},
    {"code": "TP", "value": 73, "unit": "г/л", "analysis_index": 1},
    {"code": "TP", "value": 74, "unit": "г/л", "analysis_index": 2},
    {"code": "TP", "value": 73.5, "unit": "г/л", "analysis_index": 3},
    {"code": "NA", "value": 141, "unit": "ммоль/л", "analysis_index": 0},
    {"code": "NA", "value": 140, "unit": "ммоль/л", "analysis_index": 1},
    {"code": "NA", "value": 139, "unit": "ммоль/л", "analysis_index": 2},
    {"code": "NA", "value": 140, "unit": "ммоль/л", "analysis_index": 3},
    {"code": "K", "value": 4.5, "unit": "ммоль/л", "analysis_index": 0},
    {"code": "K", "value": 4.4, "unit": "ммоль/л", "analysis_index": 1},
    {"code": "K", "value": 4.3, "unit": "ммоль/л", "analysis_index": 2},
    {"code": "K", "value": 4.3, "unit": "ммоль/л", "analysis_index": 3},
    {"code": "CL", "value": 102, "unit": "ммоль/л", "analysis_index": 0},
    {"code": "CL", "value": 101, "unit": "ммоль/л", "analysis_index": 1},
    {"code": "CL", "value": 100, "unit": "ммоль/л", "analysis_index": 2},
    {"code": "CL", "value": 100, "unit": "ммоль/л", "analysis_index": 3},
    {"code": "CACL", "value": 2.4, "unit": "ммоль/л", "analysis_index": 0},
    {"code": "CACL", "value": 2.42, "unit": "ммоль/л", "analysis_index": 1},
    {"code": "CACL", "value": 2.45, "unit": "ммоль/л", "analysis_index": 2},
    {"code": "CACL", "value": 2.43, "unit": "ммоль/л", "analysis_index": 3},
    {"code": "TEST", "value": 11, "unit": "нмоль/л", "analysis_index": 0},
    {"code": "TEST", "value": 13.5, "unit": "нмоль/л", "analysis_index": 1},
    {"code": "TEST", "value": 15.2, "unit": "нмоль/л", "analysis_index": 2},
    {"code": "TEST", "value": 14.5, "unit": "нмоль/л", "analysis_index": 3},
    {"code": "SHBG", "value": 38, "unit": "нмоль/л", "analysis_index": 0},
    {"code": "SHBG", "value": 35, "unit": "нмоль/л", "analysis_index": 1},
    {"code": "SHBG", "value": 32, "unit": "нмоль/л", "analysis_index": 2},
    {"code": "SHBG", "value": 33, "unit": "нмоль/л", "analysis_index": 3},
    {"code": "DHEAS", "value": 180, "unit": "мкг/дл", "analysis_index": 0},
    {"code": "DHEAS", "value": 195, "unit": "мкг/дл", "analysis_index": 1},
    {"code": "DHEAS", "value": 210, "unit": "мкг/дл", "analysis_index": 2},
    {"code": "DHEAS", "value": 205, "unit": "мкг/дл", "analysis_index": 3},
    {"code": "VITD", "value": 32, "unit": "нг/мл", "analysis_index": 0},
    {"code": "VITD", "value": 48, "unit": "нг/мл", "analysis_index": 1},
    {"code": "VITD", "value": 62, "unit": "нг/мл", "analysis_index": 2},
    {"code": "VITD", "value": 58, "unit": "нг/мл", "analysis_index": 3},
    {"code": "TSH", "value": 2.2, "unit": "мМЕ/л", "analysis_index": 0},
    {"code": "TSH", "value": 2.0, "unit": "мМЕ/л", "analysis_index": 1},
    {"code": "TSH", "value": 1.8, "unit": "мМЕ/л", "analysis_index": 2},
    {"code": "TSH", "value": 1.9, "unit": "мМЕ/л", "analysis_index": 3},
    {"code": "FT4", "value": 14, "unit": "пмоль/л", "analysis_index": 0},
    {"code": "FT4", "value": 14.5, "unit": "пмоль/л", "analysis_index": 1},
    {"code": "FT4", "value": 15, "unit": "пмоль/л", "analysis_index": 2},
    {"code": "FT4", "value": 14.8, "unit": "пмоль/л", "analysis_index": 3},
    {"code": "FT3", "value": 4.2, "unit": "пмоль/л", "analysis_index": 0},
    {"code": "FT3", "value": 4.4, "unit": "пмоль/л", "analysis_index": 1},
    {"code": "FT3", "value": 4.6, "unit": "пмоль/л", "analysis_index": 2},
    {"code": "FT3", "value": 4.5, "unit": "пмоль/л", "analysis_index": 3},
    {"code": "CORT", "value": 420, "unit": "нмоль/л", "analysis_index": 0},
    {"code": "CORT", "value": 390, "unit": "нмоль/л", "analysis_index": 1},
    {"code": "CORT", "value": 360, "unit": "нмоль/л", "analysis_index": 2},
    {"code": "CORT", "value": 375, "unit": "нмоль/л", "analysis_index": 3},
    {"code": "IGF1", "value": 145, "unit": "нг/мл", "analysis_index": 0},
    {"code": "IGF1", "value": 158, "unit": "нг/мл", "analysis_index": 1},
    {"code": "IGF1", "value": 168, "unit": "нг/мл", "analysis_index": 2},
    {"code": "IGF1", "value": 165, "unit": "нг/мл", "analysis_index": 3}
  ]
}'::jsonb,
female_data = '{
  "profile": {
    "name": "Мария Иванова",
    "gender": "female",
    "birth_date": "1980-03-20",
    "weight": 68,
    "height": 165
  },
  "analyses": [
    {
      "date": "2024-04-15",
      "note": "Первичное обследование",
      "lab_name": "Медицинский центр \"Здоровье\"",
      "biological_age": 49,
      "health_index": 66,
      "status": "processed",
      "analysis_index": 0
    },
    {
      "date": "2024-07-15",
      "note": "Контрольное обследование через 3 месяца",
      "lab_name": "Медицинский центр \"Здоровье\"",
      "biological_age": 47.5,
      "health_index": 71,
      "status": "processed",
      "analysis_index": 1
    },
    {
      "date": "2024-10-15",
      "note": "Повторное обследование",
      "lab_name": "Медицинский центр \"Здоровье\"",
      "biological_age": 46,
      "health_index": 77,
      "status": "processed",
      "analysis_index": 2
    },
    {
      "date": "2025-01-15",
      "note": "Плановое обследование",
      "lab_name": "Медицинский центр \"Здоровье\"",
      "biological_age": 46.5,
      "health_index": 75,
      "status": "processed",
      "analysis_index": 3
    }
  ],
  "biomarkers": [
    {"code": "HB", "value": 125, "unit": "г/л", "analysis_index": 0},
    {"code": "HB", "value": 130, "unit": "г/л", "analysis_index": 1},
    {"code": "HB", "value": 135, "unit": "г/л", "analysis_index": 2},
    {"code": "HB", "value": 133, "unit": "г/л", "analysis_index": 3},
    {"code": "RBC", "value": 4.1, "unit": "×10¹²/л", "analysis_index": 0},
    {"code": "RBC", "value": 4.3, "unit": "×10¹²/л", "analysis_index": 1},
    {"code": "RBC", "value": 4.5, "unit": "×10¹²/л", "analysis_index": 2},
    {"code": "RBC", "value": 4.4, "unit": "×10¹²/л", "analysis_index": 3},
    {"code": "HCT", "value": 37, "unit": "%", "analysis_index": 0},
    {"code": "HCT", "value": 39, "unit": "%", "analysis_index": 1},
    {"code": "HCT", "value": 41, "unit": "%", "analysis_index": 2},
    {"code": "HCT", "value": 40, "unit": "%", "analysis_index": 3},
    {"code": "MCV", "value": 88, "unit": "фл", "analysis_index": 0},
    {"code": "MCV", "value": 89, "unit": "фл", "analysis_index": 1},
    {"code": "MCV", "value": 90, "unit": "фл", "analysis_index": 2},
    {"code": "MCV", "value": 90, "unit": "фл", "analysis_index": 3},
    {"code": "MCHC", "value": 27, "unit": "пг", "analysis_index": 0},
    {"code": "MCHC", "value": 28, "unit": "пг", "analysis_index": 1},
    {"code": "MCHC", "value": 29, "unit": "пг", "analysis_index": 2},
    {"code": "MCHC", "value": 28.5, "unit": "пг", "analysis_index": 3},
    {"code": "PLT", "value": 265, "unit": "×10⁹/л", "analysis_index": 0},
    {"code": "PLT", "value": 270, "unit": "×10⁹/л", "analysis_index": 1},
    {"code": "PLT", "value": 275, "unit": "×10⁹/л", "analysis_index": 2},
    {"code": "PLT", "value": 272, "unit": "×10⁹/л", "analysis_index": 3},
    {"code": "ESR", "value": 18, "unit": "мм/ч", "analysis_index": 0},
    {"code": "ESR", "value": 15, "unit": "мм/ч", "analysis_index": 1},
    {"code": "ESR", "value": 12, "unit": "мм/ч", "analysis_index": 2},
    {"code": "ESR", "value": 13, "unit": "мм/ч", "analysis_index": 3},
    {"code": "FERR", "value": 18, "unit": "нг/мл", "analysis_index": 0},
    {"code": "FERR", "value": 32, "unit": "нг/мл", "analysis_index": 1},
    {"code": "FERR", "value": 48, "unit": "нг/мл", "analysis_index": 2},
    {"code": "FERR", "value": 45, "unit": "нг/мл", "analysis_index": 3},
    {"code": "FE", "value": 8, "unit": "мкмоль/л", "analysis_index": 0},
    {"code": "FE", "value": 12, "unit": "мкмоль/л", "analysis_index": 1},
    {"code": "FE", "value": 15, "unit": "мкмоль/л", "analysis_index": 2},
    {"code": "FE", "value": 14, "unit": "мкмоль/л", "analysis_index": 3},
    {"code": "TIBC", "value": 68, "unit": "мкмоль/л", "analysis_index": 0},
    {"code": "TIBC", "value": 64, "unit": "мкмоль/л", "analysis_index": 1},
    {"code": "TIBC", "value": 60, "unit": "мкмоль/л", "analysis_index": 2},
    {"code": "TIBC", "value": 61, "unit": "мкмоль/л", "analysis_index": 3},
    {"code": "TRANSF", "value": 2.1, "unit": "г/л", "analysis_index": 0},
    {"code": "TRANSF", "value": 2.4, "unit": "г/л", "analysis_index": 1},
    {"code": "TRANSF", "value": 2.7, "unit": "г/л", "analysis_index": 2},
    {"code": "TRANSF", "value": 2.6, "unit": "г/л", "analysis_index": 3},
    {"code": "TSAT", "value": 12, "unit": "%", "analysis_index": 0},
    {"code": "TSAT", "value": 18, "unit": "%", "analysis_index": 1},
    {"code": "TSAT", "value": 24, "unit": "%", "analysis_index": 2},
    {"code": "TSAT", "value": 22, "unit": "%", "analysis_index": 3},
    {"code": "RETIC", "value": 1.5, "unit": "%", "analysis_index": 0},
    {"code": "RETIC", "value": 1.3, "unit": "%", "analysis_index": 1},
    {"code": "RETIC", "value": 1.1, "unit": "%", "analysis_index": 2},
    {"code": "RETIC", "value": 1.2, "unit": "%", "analysis_index": 3},
    {"code": "HAPTO", "value": 1.1, "unit": "г/л", "analysis_index": 0},
    {"code": "HAPTO", "value": 1.2, "unit": "г/л", "analysis_index": 1},
    {"code": "HAPTO", "value": 1.3, "unit": "г/л", "analysis_index": 2},
    {"code": "HAPTO", "value": 1.25, "unit": "г/л", "analysis_index": 3},
    {"code": "FOLATE", "value": 6, "unit": "нг/мл", "analysis_index": 0},
    {"code": "FOLATE", "value": 8, "unit": "нг/мл", "analysis_index": 1},
    {"code": "FOLATE", "value": 10, "unit": "нг/мл", "analysis_index": 2},
    {"code": "FOLATE", "value": 9, "unit": "нг/мл", "analysis_index": 3},
    {"code": "WBC", "value": 6.8, "unit": "×10⁹/л", "analysis_index": 0},
    {"code": "WBC", "value": 6.5, "unit": "×10⁹/л", "analysis_index": 1},
    {"code": "WBC", "value": 6.1, "unit": "×10⁹/л", "analysis_index": 2},
    {"code": "WBC", "value": 6.2, "unit": "×10⁹/л", "analysis_index": 3},
    {"code": "NEUT", "value": 63, "unit": "%", "analysis_index": 0},
    {"code": "NEUT", "value": 61, "unit": "%", "analysis_index": 1},
    {"code": "NEUT", "value": 59, "unit": "%", "analysis_index": 2},
    {"code": "NEUT", "value": 60, "unit": "%", "analysis_index": 3},
    {"code": "LYMPH", "value": 27, "unit": "%", "analysis_index": 0},
    {"code": "LYMPH", "value": 29, "unit": "%", "analysis_index": 1},
    {"code": "LYMPH", "value": 31, "unit": "%", "analysis_index": 2},
    {"code": "LYMPH", "value": 30, "unit": "%", "analysis_index": 3},
    {"code": "MONO", "value": 7, "unit": "%", "analysis_index": 0},
    {"code": "MONO", "value": 6.5, "unit": "%", "analysis_index": 1},
    {"code": "MONO", "value": 6, "unit": "%", "analysis_index": 2},
    {"code": "MONO", "value": 6, "unit": "%", "analysis_index": 3},
    {"code": "EOS", "value": 2, "unit": "%", "analysis_index": 0},
    {"code": "EOS", "value": 2.5, "unit": "%", "analysis_index": 1},
    {"code": "EOS", "value": 3, "unit": "%", "analysis_index": 2},
    {"code": "EOS", "value": 3, "unit": "%", "analysis_index": 3},
    {"code": "BASO", "value": 0.5, "unit": "%", "analysis_index": 0},
    {"code": "BASO", "value": 0.5, "unit": "%", "analysis_index": 1},
    {"code": "BASO", "value": 0.5, "unit": "%", "analysis_index": 2},
    {"code": "BASO", "value": 0.5, "unit": "%", "analysis_index": 3},
    {"code": "CRP", "value": 5.2, "unit": "мг/л", "analysis_index": 0},
    {"code": "CRP", "value": 3.8, "unit": "мг/л", "analysis_index": 1},
    {"code": "CRP", "value": 2.5, "unit": "мг/л", "analysis_index": 2},
    {"code": "CRP", "value": 2.9, "unit": "мг/л", "analysis_index": 3},
    {"code": "IL6", "value": 7.2, "unit": "пг/мл", "analysis_index": 0},
    {"code": "IL6", "value": 5.8, "unit": "пг/мл", "analysis_index": 1},
    {"code": "IL6", "value": 4.2, "unit": "пг/мл", "analysis_index": 2},
    {"code": "IL6", "value": 4.6, "unit": "пг/мл", "analysis_index": 3},
    {"code": "TNF", "value": 8.5, "unit": "пг/мл", "analysis_index": 0},
    {"code": "TNF", "value": 6.8, "unit": "пг/мл", "analysis_index": 1},
    {"code": "TNF", "value": 5.2, "unit": "пг/мл", "analysis_index": 2},
    {"code": "TNF", "value": 5.6, "unit": "пг/мл", "analysis_index": 3},
    {"code": "IGM", "value": 1.3, "unit": "г/л", "analysis_index": 0},
    {"code": "IGM", "value": 1.4, "unit": "г/л", "analysis_index": 1},
    {"code": "IGM", "value": 1.5, "unit": "г/л", "analysis_index": 2},
    {"code": "IGM", "value": 1.45, "unit": "г/л", "analysis_index": 3},
    {"code": "IGG", "value": 12, "unit": "г/л", "analysis_index": 0},
    {"code": "IGG", "value": 12.5, "unit": "г/л", "analysis_index": 1},
    {"code": "IGG", "value": 13, "unit": "г/л", "analysis_index": 2},
    {"code": "IGG", "value": 12.8, "unit": "г/л", "analysis_index": 3},
    {"code": "IGA", "value": 2.4, "unit": "г/л", "analysis_index": 0},
    {"code": "IGA", "value": 2.5, "unit": "г/л", "analysis_index": 1},
    {"code": "IGA", "value": 2.6, "unit": "г/л", "analysis_index": 2},
    {"code": "IGA", "value": 2.55, "unit": "г/л", "analysis_index": 3},
    {"code": "IGE", "value": 52, "unit": "МЕ/мл", "analysis_index": 0},
    {"code": "IGE", "value": 48, "unit": "МЕ/мл", "analysis_index": 1},
    {"code": "IGE", "value": 42, "unit": "МЕ/мл", "analysis_index": 2},
    {"code": "IGE", "value": 45, "unit": "МЕ/мл", "analysis_index": 3},
    {"code": "CD3", "value": 65, "unit": "%", "analysis_index": 0},
    {"code": "CD3", "value": 68, "unit": "%", "analysis_index": 1},
    {"code": "CD3", "value": 70, "unit": "%", "analysis_index": 2},
    {"code": "CD3", "value": 69, "unit": "%", "analysis_index": 3},
    {"code": "CD4", "value": 40, "unit": "%", "analysis_index": 0},
    {"code": "CD4", "value": 42, "unit": "%", "analysis_index": 1},
    {"code": "CD4", "value": 44, "unit": "%", "analysis_index": 2},
    {"code": "CD4", "value": 43, "unit": "%", "analysis_index": 3},
    {"code": "CD8", "value": 26, "unit": "%", "analysis_index": 0},
    {"code": "CD8", "value": 26, "unit": "%", "analysis_index": 1},
    {"code": "CD8", "value": 25, "unit": "%", "analysis_index": 2},
    {"code": "CD8", "value": 25, "unit": "%", "analysis_index": 3},
    {"code": "CD19", "value": 13, "unit": "%", "analysis_index": 0},
    {"code": "CD19", "value": 14, "unit": "%", "analysis_index": 1},
    {"code": "CD19", "value": 15, "unit": "%", "analysis_index": 2},
    {"code": "CD19", "value": 14.5, "unit": "%", "analysis_index": 3},
    {"code": "NK", "value": 14, "unit": "%", "analysis_index": 0},
    {"code": "NK", "value": 15, "unit": "%", "analysis_index": 1},
    {"code": "NK", "value": 16, "unit": "%", "analysis_index": 2},
    {"code": "NK", "value": 15.5, "unit": "%", "analysis_index": 3},
    {"code": "CHOL", "value": 6.4, "unit": "ммоль/л", "analysis_index": 0},
    {"code": "CHOL", "value": 5.9, "unit": "ммоль/л", "analysis_index": 1},
    {"code": "CHOL", "value": 5.4, "unit": "ммоль/л", "analysis_index": 2},
    {"code": "CHOL", "value": 5.6, "unit": "ммоль/л", "analysis_index": 3},
    {"code": "LDL", "value": 4.3, "unit": "ммоль/л", "analysis_index": 0},
    {"code": "LDL", "value": 3.8, "unit": "ммоль/л", "analysis_index": 1},
    {"code": "LDL", "value": 3.3, "unit": "ммоль/л", "analysis_index": 2},
    {"code": "LDL", "value": 3.5, "unit": "ммоль/л", "analysis_index": 3},
    {"code": "HDL", "value": 1.3, "unit": "ммоль/л", "analysis_index": 0},
    {"code": "HDL", "value": 1.4, "unit": "ммоль/л", "analysis_index": 1},
    {"code": "HDL", "value": 1.5, "unit": "ммоль/л", "analysis_index": 2},
    {"code": "HDL", "value": 1.45, "unit": "ммоль/л", "analysis_index": 3},
    {"code": "TG", "value": 1.8, "unit": "ммоль/л", "analysis_index": 0},
    {"code": "TG", "value": 1.6, "unit": "ммоль/л", "analysis_index": 1},
    {"code": "TG", "value": 1.3, "unit": "ммоль/л", "analysis_index": 2},
    {"code": "TG", "value": 1.4, "unit": "ммоль/л", "analysis_index": 3},
    {"code": "VLDL", "value": 0.82, "unit": "ммоль/л", "analysis_index": 0},
    {"code": "VLDL", "value": 0.73, "unit": "ммоль/л", "analysis_index": 1},
    {"code": "VLDL", "value": 0.59, "unit": "ммоль/л", "analysis_index": 2},
    {"code": "VLDL", "value": 0.64, "unit": "ммоль/л", "analysis_index": 3},
    {"code": "APOA1", "value": 1.4, "unit": "г/л", "analysis_index": 0},
    {"code": "APOA1", "value": 1.5, "unit": "г/л", "analysis_index": 1},
    {"code": "APOA1", "value": 1.6, "unit": "г/л", "analysis_index": 2},
    {"code": "APOA1", "value": 1.55, "unit": "г/л", "analysis_index": 3},
    {"code": "APOB", "value": 1.2, "unit": "г/л", "analysis_index": 0},
    {"code": "APOB", "value": 1.1, "unit": "г/л", "analysis_index": 1},
    {"code": "APOB", "value": 0.98, "unit": "г/л", "analysis_index": 2},
    {"code": "APOB", "value": 1.02, "unit": "г/л", "analysis_index": 3},
    {"code": "CA", "value": 3.9, "unit": "усл.ед.", "analysis_index": 0},
    {"code": "CA", "value": 3.2, "unit": "усл.ед.", "analysis_index": 2},
    {"code": "CA", "value": 2.6, "unit": "усл.ед.", "analysis_index": 2},
    {"code": "CA", "value": 2.9, "unit": "усл.ед.", "analysis_index": 3},
    {"code": "LPA", "value": 32, "unit": "мг/дл", "analysis_index": 0},
    {"code": "LPA", "value": 29, "unit": "мг/дл", "analysis_index": 1},
    {"code": "LPA", "value": 26, "unit": "мг/дл", "analysis_index": 2},
    {"code": "LPA", "value": 27, "unit": "мг/дл", "analysis_index": 3},
    {"code": "HCY", "value": 12, "unit": "мкмоль/л", "analysis_index": 0},
    {"code": "HCY", "value": 10, "unit": "мкмоль/л", "analysis_index": 1},
    {"code": "HCY", "value": 9, "unit": "мкмоль/л", "analysis_index": 2},
    {"code": "HCY", "value": 9.5, "unit": "мкмоль/л", "analysis_index": 3},
    {"code": "NTPROBNP", "value": 92, "unit": "пг/мл", "analysis_index": 0},
    {"code": "NTPROBNP", "value": 85, "unit": "пг/мл", "analysis_index": 1},
    {"code": "NTPROBNP", "value": 78, "unit": "пг/мл", "analysis_index": 2},
    {"code": "NTPROBNP", "value": 80, "unit": "пг/мл", "analysis_index": 3},
    {"code": "TROP", "value": 0.009, "unit": "нг/мл", "analysis_index": 0},
    {"code": "TROP", "value": 0.008, "unit": "нг/мл", "analysis_index": 1},
    {"code": "TROP", "value": 0.007, "unit": "нг/мл", "analysis_index": 2},
    {"code": "TROP", "value": 0.007, "unit": "нг/мл", "analysis_index": 3},
    {"code": "MYO", "value": 38, "unit": "нг/мл", "analysis_index": 0},
    {"code": "MYO", "value": 35, "unit": "нг/мл", "analysis_index": 1},
    {"code": "MYO", "value": 32, "unit": "нг/мл", "analysis_index": 2},
    {"code": "MYO", "value": 33, "unit": "нг/мл", "analysis_index": 3},
    {"code": "CPK", "value": 145, "unit": "Ед/л", "analysis_index": 0},
    {"code": "CPK", "value": 138, "unit": "Ед/л", "analysis_index": 1},
    {"code": "CPK", "value": 132, "unit": "Ед/л", "analysis_index": 2},
    {"code": "CPK", "value": 135, "unit": "Ед/л", "analysis_index": 3},
    {"code": "LDH", "value": 195, "unit": "Ед/л", "analysis_index": 0},
    {"code": "LDH", "value": 188, "unit": "Ед/л", "analysis_index": 1},
    {"code": "LDH", "value": 182, "unit": "Ед/л", "analysis_index": 2},
    {"code": "LDH", "value": 185, "unit": "Ед/л", "analysis_index": 3},
    {"code": "GLU", "value": 5.8, "unit": "ммоль/л", "analysis_index": 0},
    {"code": "GLU", "value": 5.5, "unit": "ммоль/л", "analysis_index": 1},
    {"code": "GLU", "value": 5.2, "unit": "ммоль/л", "analysis_index": 2},
    {"code": "GLU", "value": 5.3, "unit": "ммоль/л", "analysis_index": 3},
    {"code": "HBA1C", "value": 5.9, "unit": "%", "analysis_index": 0},
    {"code": "HBA1C", "value": 5.6, "unit": "%", "analysis_index": 1},
    {"code": "HBA1C", "value": 5.4, "unit": "%", "analysis_index": 2},
    {"code": "HBA1C", "value": 5.5, "unit": "%", "analysis_index": 3},
    {"code": "INS", "value": 15, "unit": "мкЕд/мл", "analysis_index": 0},
    {"code": "INS", "value": 12, "unit": "мкЕд/мл", "analysis_index": 1},
    {"code": "INS", "value": 10, "unit": "мкЕд/мл", "analysis_index": 2},
    {"code": "INS", "value": 11, "unit": "мкЕд/мл", "analysis_index": 3},
    {"code": "CREA", "value": 72, "unit": "мкмоль/л", "analysis_index": 0},
    {"code": "CREA", "value": 70, "unit": "мкмоль/л", "analysis_index": 1},
    {"code": "CREA", "value": 68, "unit": "мкмоль/л", "analysis_index": 2},
    {"code": "CREA", "value": 69, "unit": "мкмоль/л", "analysis_index": 3},
    {"code": "UREA", "value": 5.2, "unit": "ммоль/л", "analysis_index": 0},
    {"code": "UREA", "value": 4.9, "unit": "ммоль/л", "analysis_index": 1},
    {"code": "UREA", "value": 4.6, "unit": "ммоль/л", "analysis_index": 2},
    {"code": "UREA", "value": 4.7, "unit": "ммоль/л", "analysis_index": 3},
    {"code": "ALT", "value": 32, "unit": "Ед/л", "analysis_index": 0},
    {"code": "ALT", "value": 28, "unit": "Ед/л", "analysis_index": 1},
    {"code": "ALT", "value": 24, "unit": "Ед/л", "analysis_index": 2},
    {"code": "ALT", "value": 26, "unit": "Ед/л", "analysis_index": 3},
    {"code": "AST", "value": 30, "unit": "Ед/л", "analysis_index": 0},
    {"code": "AST", "value": 26, "unit": "Ед/л", "analysis_index": 1},
    {"code": "AST", "value": 22, "unit": "Ед/л", "analysis_index": 2},
    {"code": "AST", "value": 24, "unit": "Ед/л", "analysis_index": 3},
    {"code": "GGT", "value": 38, "unit": "Ед/л", "analysis_index": 0},
    {"code": "GGT", "value": 32, "unit": "Ед/л", "analysis_index": 1},
    {"code": "GGT", "value": 26, "unit": "Ед/л", "analysis_index": 2},
    {"code": "GGT", "value": 28, "unit": "Ед/л", "analysis_index": 3},
    {"code": "ALP", "value": 82, "unit": "Ед/л", "analysis_index": 0},
    {"code": "ALP", "value": 78, "unit": "Ед/л", "analysis_index": 1},
    {"code": "ALP", "value": 74, "unit": "Ед/л", "analysis_index": 2},
    {"code": "ALP", "value": 76, "unit": "Ед/л", "analysis_index": 3},
    {"code": "BIL", "value": 14, "unit": "мкмоль/л", "analysis_index": 0},
    {"code": "BIL", "value": 13, "unit": "мкмоль/л", "analysis_index": 1},
    {"code": "BIL", "value": 12, "unit": "мкмоль/л", "analysis_index": 2},
    {"code": "BIL", "value": 12.5, "unit": "мкмоль/л", "analysis_index": 3},
    {"code": "TP", "value": 70, "unit": "г/л", "analysis_index": 0},
    {"code": "TP", "value": 71, "unit": "г/л", "analysis_index": 1},
    {"code": "TP", "value": 72, "unit": "г/л", "analysis_index": 2},
    {"code": "TP", "value": 71.5, "unit": "г/л", "analysis_index": 3},
    {"code": "NA", "value": 140, "unit": "ммоль/л", "analysis_index": 0},
    {"code": "NA", "value": 139, "unit": "ммоль/л", "analysis_index": 1},
    {"code": "NA", "value": 138, "unit": "ммоль/л", "analysis_index": 2},
    {"code": "NA", "value": 139, "unit": "ммоль/л", "analysis_index": 3},
    {"code": "K", "value": 4.4, "unit": "ммоль/л", "analysis_index": 0},
    {"code": "K", "value": 4.3, "unit": "ммоль/л", "analysis_index": 1},
    {"code": "K", "value": 4.2, "unit": "ммоль/л", "analysis_index": 2},
    {"code": "K", "value": 4.2, "unit": "ммоль/л", "analysis_index": 3},
    {"code": "CL", "value": 101, "unit": "ммоль/л", "analysis_index": 0},
    {"code": "CL", "value": 100, "unit": "ммоль/л", "analysis_index": 1},
    {"code": "CL", "value": 99, "unit": "ммоль/л", "analysis_index": 2},
    {"code": "CL", "value": 99, "unit": "ммоль/л", "analysis_index": 3},
    {"code": "CACL", "value": 2.38, "unit": "ммоль/л", "analysis_index": 0},
    {"code": "CACL", "value": 2.41, "unit": "ммоль/л", "analysis_index": 1},
    {"code": "CACL", "value": 2.44, "unit": "ммоль/л", "analysis_index": 2},
    {"code": "CACL", "value": 2.42, "unit": "ммоль/л", "analysis_index": 3},
    {"code": "ESTR", "value": 45, "unit": "пг/мл", "analysis_index": 0},
    {"code": "ESTR", "value": 62, "unit": "пг/мл", "analysis_index": 1},
    {"code": "ESTR", "value": 78, "unit": "пг/мл", "analysis_index": 2},
    {"code": "ESTR", "value": 72, "unit": "пг/мл", "analysis_index": 3},
    {"code": "SHBG", "value": 58, "unit": "нмоль/л", "analysis_index": 0},
    {"code": "SHBG", "value": 54, "unit": "нмоль/л", "analysis_index": 1},
    {"code": "SHBG", "value": 50, "unit": "нмоль/л", "analysis_index": 2},
    {"code": "SHBG", "value": 52, "unit": "нмоль/л", "analysis_index": 3},
    {"code": "DHEAS", "value": 95, "unit": "мкг/дл", "analysis_index": 0},
    {"code": "DHEAS", "value": 110, "unit": "мкг/дл", "analysis_index": 1},
    {"code": "DHEAS", "value": 125, "unit": "мкг/дл", "analysis_index": 2},
    {"code": "DHEAS", "value": 120, "unit": "мкг/дл", "analysis_index": 3},
    {"code": "VITD", "value": 28, "unit": "нг/мл", "analysis_index": 0},
    {"code": "VITD", "value": 42, "unit": "нг/мл", "analysis_index": 1},
    {"code": "VITD", "value": 56, "unit": "нг/мл", "analysis_index": 2},
    {"code": "VITD", "value": 52, "unit": "нг/мл", "analysis_index": 3},
    {"code": "TSH", "value": 3.8, "unit": "мМЕ/л", "analysis_index": 0},
    {"code": "TSH", "value": 3.2, "unit": "мМЕ/л", "analysis_index": 1},
    {"code": "TSH", "value": 2.6, "unit": "мМЕ/л", "analysis_index": 2},
    {"code": "TSH", "value": 2.8, "unit": "мМЕ/л", "analysis_index": 3},
    {"code": "FT4", "value": 12, "unit": "пмоль/л", "analysis_index": 0},
    {"code": "FT4", "value": 13, "unit": "пмоль/л", "analysis_index": 1},
    {"code": "FT4", "value": 14, "unit": "пмоль/л", "analysis_index": 2},
    {"code": "FT4", "value": 13.5, "unit": "пмоль/л", "analysis_index": 3},
    {"code": "FT3", "value": 3.8, "unit": "пмоль/л", "analysis_index": 0},
    {"code": "FT3", "value": 4.1, "unit": "пмоль/л", "analysis_index": 1},
    {"code": "FT3", "value": 4.4, "unit": "пмоль/л", "analysis_index": 2},
    {"code": "FT3", "value": 4.2, "unit": "пмоль/л", "analysis_index": 3},
    {"code": "CORT", "value": 480, "unit": "нмоль/л", "analysis_index": 0},
    {"code": "CORT", "value": 440, "unit": "нмоль/л", "analysis_index": 1},
    {"code": "CORT", "value": 400, "unit": "нмоль/л", "analysis_index": 2},
    {"code": "CORT", "value": 420, "unit": "нмоль/л", "analysis_index": 3},
    {"code": "IGF1", "value": 128, "unit": "нг/мл", "analysis_index": 0},
    {"code": "IGF1", "value": 142, "unit": "нг/мл", "analysis_index": 1},
    {"code": "IGF1", "value": 155, "unit": "нг/мл", "analysis_index": 2},
    {"code": "IGF1", "value": 150, "unit": "нг/мл", "analysis_index": 3}
  ]
}'::jsonb
WHERE id = 'default';